version: '3.8'

networks:
  mynetwork:
    driver: bridge

volumes:
  grafana_data:
  prometheus_data:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: MY_GRAFANA
    ports:
      - 8000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: MY_PROMETHEUS
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/data:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - cadvisor
    networks:
      - mynetwork

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: MY_CADVISOR
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: MY_REDIS
    ports:
      - 6379:6379
    networks:
      - mynetwork